title: "RRPR 2026"
description: "Sixth Workshop on Reproducible Research in Pattern Recognition"
baseurl: ""
url: "https://TC22-Team.github.io/rrpr2026"

plugins: #[]
   - jekyll-seo-tag
sass:
  sass_dir: _sass
  style: expanded




